# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/braided-course-452006-i9/tsmc-backend
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secret
       

