name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint-and-format:
    # ✅ 排除 push 到 production 分支
    # ✅ 排除 PR 的目標是 production 分支
    if: |
      github.ref != 'refs/heads/production' &&
      github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for Project
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Project Dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run Project Linter
        run: yarn lint
        working-directory: ./frontend

      - name: Run Project Prettier Check
        run: yarn prettier --check .
        working-directory: ./frontend
