name: Run Backend Tests

on: [push, pull_request]

jobs:
  test:
    # ✅ 排除 push 到 production 分支
    # ✅ 排除 PR 指向 production 分支
    if: |
      github.ref != 'refs/heads/production' &&
      github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'production'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r backend/requirements.txt
    
    - name: Set environment variables
      run: |
        echo "DB_PORT=3306" >> $GITHUB_ENV
        echo "DB_HOST=34.81.245.163" >> $GITHUB_ENV
        echo "DB_USER=backend_user" >> $GITHUB_ENV
        echo "DB_PASSWORD=StrongPassword123!" >> $GITHUB_ENV
        echo "DB_NAME=leave_management" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/backend/src" >> $GITHUB_ENV

     
    - name: Run tests
      run: PYTHONPATH=backend/src pytest -s backend/tests/
